name: Build Artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
    outputs:
      version: 
        description: "Version builded"
        value: ${{ jobs.build.outputs.version }}
jobs:
  build:
    name: Build
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      SolutionName: ModpacksCH.sln
      Configuration: ${{ matrix.configuration }}
    outputs:
      version: ${{steps.version.outputs.version}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Set VERSION
      id: version
      run: |
        dotnet tool install -g minver-cli --version 2.5.0
        $version = minver -t v -d preview
        $number = $version.Split('-')[0]
        echo "VERSION=$version"
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "::set-output name=version::$version"

    - name: Build solution
      run: dotnet build -c $env:Configuration
        
    - name: Build artifact
      if: matrix.configuration == 'Release'
      run: |
        dotnet publish -c Release -p:PublishProfile=win-x64 /property:Version=$env:VERSION
        dotnet publish -c Release -p:PublishProfile=linux-x64 /property:Version=$env:VERSION

    - name: Upload a Build Artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ModpacksCH(win)
        path: |          
          ModpacksCH\bin\Release\net6.0\publish\win-x64\ModpacksCH.exe
        if-no-files-found: error

    - name: Upload a Build Artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ModpacksCH(linux)
        path: |
          ModpacksCH\bin\Release\net6.0\publish\linux-x64\ModpacksCH
        if-no-files-found: error