name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: Virenbar/ModpacksCH/.github/workflows/build-artifact.yml@master
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Version
        run: echo "Version builded ${{ needs.build.outputs.version }}"

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Archive artifacts
        run: |
          zip -r "ModpacksCH(Windows).zip" "ModpacksCH(win)"
          zip -r "ModpacksCH(Linux).zip" "ModpacksCH(linux)"

      # - name: LS
      #   run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ModpacksCH(Windows).zip
            ModpacksCH(Linux).zip
