name: Publish Artifact
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-artifact.yml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Version
        run: echo "Version builded ${{ needs.build.outputs.version }}"

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: LS
        run: ls -R

      - name: Archive artifacts
        run: |
          zip -r "ModpacksCH-Windows.zip" "ModpacksCH(win)"
          zip -r "ModpacksCH-Linux.zip" "ModpacksCH(linux)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ModpacksCH-Windows.zip
            ModpacksCH-Linux.zip
